version: 2

models:
  - name: my_first_dbt_model
    columns:
      - name: id
        tests:
          - not_null
          - unique

  - name: my_second_dbt_model
    columns:
      - name: id
        tests:
          - not_null
          - unique

  - name: stg_taxi_weather
    columns:
      - name: PULocationID
        tests:
          - not_null
